SOUND_NUM(step, cloth, 1)
SOUND_NUM(step, cloth, 2)
SOUND_NUM(step, cloth, 3)
SOUND_NUM(step, cloth, 4)

SOUND_NUM(step, grass, 1)
SOUND_NUM(step, grass, 2)
SOUND_NUM(step, grass, 3)
SOUND_NUM(step, grass, 4)

SOUND_NUM(step, gravel, 1)
SOUND_NUM(step, gravel, 2)
SOUND_NUM(step, gravel, 3)
SOUND_NUM(step, gravel, 4)

SOUND_NUM(step, sand, 1)
SOUND_NUM(step, sand, 2)
SOUND_NUM(step, sand, 3)
SOUND_NUM(step, sand, 4)

SOUND_NUM(step, stone, 1)
SOUND_NUM(step, stone, 2)
SOUND_NUM(step, stone, 3)
SOUND_NUM(step, stone, 4)

SOUND_NUM(step, wood, 1)
SOUND_NUM(step, wood, 2)
SOUND_NUM(step, wood, 3)
SOUND_NUM(step, wood, 4)

SOUND(random, bow)
SOUND(random, click)
SOUND(random, door_close)
SOUND(random, door_open)
SOUND(random, drr)
SOUND(random, explode)
SOUND(random, fizz)
SOUND(random, fuse)
SOUND(random, hurt)
SOUND(random, pop)
SOUND(random, splash)

SOUND(ui, back)
SOUND(ui, craft)
SOUND(ui, craftfail)
SOUND(ui, focus)
SOUND(ui, press)
SOUND(ui, scroll)

SOUND(fire, fire)
SOUND(fire, ignite)
SOUND_NUM(fire, fire_crackle, 1)
SOUND_NUM(fire, fire_crackle, 2)
SOUND_NUM(fire, fire_crackle, 3)
SOUND_NUM(fire, fire_crackle, 4)
SOUND_NUM(fire, fire_crackle, 5)

SOUND_NUM(damage, fallbig, 1)
SOUND_NUM(damage, fallbig, 2)

SOUND(damage, fallsmall)

SOUND_NUM(mob, chicken, 2)
SOUND_NUM(mob, chicken, 3)
SOUND_NUM(mob, chickenhurt, 1)
SOUND_NUM(mob, chickenhurt, 2)

SOUND_NUM(mob, cow, 1)
SOUND_NUM(mob, cow, 2)
SOUND_NUM(mob, cow, 3)
SOUND_NUM(mob, cow, 4)
SOUND_NUM(mob, cowhurt, 1)
SOUND_NUM(mob, cowhurt, 2)
SOUND_NUM(mob, cowhurt, 3)

SOUND_NUM(mob, creeper, 1)
SOUND_NUM(mob, creeper, 2)
SOUND_NUM(mob, creeper, 3)
SOUND_NUM(mob, creeper, 4)
SOUND(mob, creeperdeath)

SOUND(mob.ghast, charge)
SOUND(mob.ghast, death)
SOUND_NUM(mob.ghast, fireball, 4)
SOUND_NUM(mob.ghast, moan, 1)
SOUND_NUM(mob.ghast, moan, 2)
SOUND_NUM(mob.ghast, moan, 3)
SOUND_NUM(mob.ghast, moan, 4)
SOUND_NUM(mob.ghast, moan, 5)
SOUND_NUM(mob.ghast, moan, 6)
SOUND_NUM(mob.ghast, moan, 7)
SOUND_NUM(mob.ghast, scream, 1)
SOUND_NUM(mob.ghast, scream, 2)
SOUND_NUM(mob.ghast, scream, 3)
SOUND_NUM(mob.ghast, scream, 4)
SOUND_NUM(mob.ghast, scream, 5)

SOUND_NUM(mob, pig, 1)
SOUND_NUM(mob, pig, 2)
SOUND_NUM(mob, pig, 3)
SOUND(mob, pigdeath)

SOUND_NUM(mob, sheep, 1)
SOUND_NUM(mob, sheep, 2)
SOUND_NUM(mob, sheep, 3)

SOUND_NUM(mob, skeleton, 1)
SOUND_NUM(mob, skeleton, 2)
SOUND_NUM(mob, skeleton, 3)
SOUND_NUM(mob, skeletonhurt, 1)
SOUND_NUM(mob, skeletonhurt, 2)
SOUND_NUM(mob, skeletonhurt, 3)
SOUND_NUM(mob, skeletonhurt, 4)
SOUND(mob, skeletondeath)

SOUND_NUM(mob, slime, 1)
SOUND_NUM(mob, slime, 2)
SOUND_NUM(mob, slime, 3)
SOUND_NUM(mob, slime, 4)
SOUND_NUM(mob, slime, 5)
SOUND_NUM(mob, slimeattack, 1)
SOUND_NUM(mob, slimeattack, 2)

SOUND_NUM(mob, spider, 1)
SOUND_NUM(mob, spider, 2)
SOUND_NUM(mob, spider, 3)
SOUND_NUM(mob, spider, 4)
SOUND(mob, spiderdeath)

SOUND_NUM(mob, zombie, 1)
SOUND_NUM(mob, zombie, 2)
SOUND_NUM(mob, zombie, 3)
SOUND_NUM(mob, zombiehurt, 1)
SOUND_NUM(mob, zombiehurt, 2)
SOUND(mob, zombiedeath)

SOUND_NUM(mob.zombiepig, zpig, 1)
SOUND_NUM(mob.zombiepig, zpig, 2)
SOUND_NUM(mob.zombiepig, zpig, 3)
SOUND_NUM(mob.zombiepig, zpig, 4)
SOUND_NUM(mob.zombiepig, zpigangry, 1)
SOUND_NUM(mob.zombiepig, zpigangry, 2)
SOUND_NUM(mob.zombiepig, zpigangry, 3)
SOUND_NUM(mob.zombiepig, zpigangry, 4)
SOUND_NUM(mob.zombiepig, zpighurt, 1)
SOUND_NUM(mob.zombiepig, zpighurt, 2)
SOUND(mob.zombiepig, zpigdeath)

SOUND_NUM(mob.wolf, growl, 1)
SOUND_NUM(mob.wolf, growl, 2)
SOUND_NUM(mob.wolf, growl, 3)
SOUND_NUM(mob.wolf, howl, 1)
SOUND_NUM(mob.wolf, howl, 2)
SOUND(mob.wolf, whine)
SOUND(mob.wolf, panting)
SOUND_NUM(mob.wolf, bark, 1)
SOUND_NUM(mob.wolf, bark, 2)
SOUND_NUM(mob.wolf, bark, 3)
SOUND(mob.wolf, shake)
SOUND_NUM(mob.wolf, hurt, 1)
SOUND_NUM(mob.wolf, hurt, 2)
SOUND_NUM(mob.wolf, hurt, 3)
//'SoundDesc SA_death': redefinition (ghast does have a sound with the same name)
//SOUND(mob.wolf, death)

SOUND_NUM(ambient.weather, rain, 1)
SOUND_NUM(ambient.weather, rain, 2)
SOUND_NUM(ambient.weather, rain, 3)
SOUND_NUM(ambient.weather, rain, 4)
SOUND_NUM(ambient.weather, thunder, 1)
SOUND_NUM(ambient.weather, thunder, 2)
SOUND_NUM(ambient.weather, thunder, 3)

SOUND(tile.piston, in)
SOUND(tile.piston, out)

SOUND(note, harp)
SOUND(note, bd)
SOUND(note, hat)
SOUND(note, snare)
SOUND(note, bassattack)